x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:

  nginx:
    build: algo-arena-fe/
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8080:8080"
    restart: always

  be:
    build: algo-arena-be/
    volumes:
        - ./problem-set:/app/problems
    env_file:
        ./judge0.conf
    restart: always
      
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./problem-set:/dev/problems
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./problem-set:/dev/problems
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
